import Head from "next/head";
import { useState } from "react";
import clsx from "clsx";

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Cliff & Sky</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Navbar */}
      <nav className="container mx-auto mb-6 flex flex-col p-6">
        {/* Flex Container */}
        <div className="mb-4 flex items-center justify-between">
          {/* Logo */}
          <h1 className="font-logo text-3xl font-bold">Cliff & Sky</h1>

          <div className={clsx("hamburger", { open: menuOpen })} onClick={() => setMenuOpen(!menuOpen)}>
            <span className="hamburger-top"></span>
            <span className="hamburger-middle"></span>
            <span className="hamburger-bottom"></span>
          </div>
        </div>
        {/* Menu Items */}
        <div>
          <ul className={clsx("flex w-full justify-between", { hidden: !menuOpen })}>
            <li className="text-lg font-bold">Portfolio</li>
            <li className="text-lg font-bold">Store</li>
            <li className="text-lg font-bold">About</li>
          </ul>
        </div>
      </nav>
    </>
  );
}
